# Aliases
docker-defaults: &docker-defaults
  docker:
    - image: quay.io/nyulibraries/circleci_docker:18.06.3-dc-1.23.2-0
      environment:
        - IMAGE_NAME=ares-templates
  working_directory: ~/app

build_docker: &build_docker
  run:
    name: Build docker
    command: |
      docker-compose build 

auth_quay: &auth_quay
  run:
    name: Authenticate Quay 
    command: |
      docker login -u "$QUAY_USERNAME" --password "$QUAY_PASSWORD" quay.io

pull_docker: &pull_docker
  run:
    name: Pull Docker
    command: |
      export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
      docker pull quay.io/nyulibraries/${IMAGE_NAME}:${BRANCH_NO_SLASH} || docker pull quay.io/nyulibraries/${IMAGE_NAME}:latest

push_docker: &push_docker
  run:
    name: Push Docker
    command: |
      export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
      docker tag ${IMAGE_NAME} quay.io/nyulibraries/${IMAGE_NAME}:latest
      docker tag ${IMAGE_NAME} quay.io/nyulibraries/${IMAGE_NAME}:${BRANCH_NO_SLASH}
      docker tag ${IMAGE_NAME} quay.io/nyulibraries/${IMAGE_NAME}:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}
      docker push quay.io/nyulibraries/${IMAGE_NAME}:latest
      docker push quay.io/nyulibraries/${IMAGE_NAME}:${BRANCH_NO_SLASH}
      docker push quay.io/nyulibraries/${IMAGE_NAME}:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}

version: 2
jobs:
  build-image:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *pull_docker
      - <<: *build_docker
      - <<: *auth_quay
      - <<: *push_docker
#  deploy-dev:
#    <<: *docker-defaults
#    steps:
#      - setup_remote_docker
#  deploy-prod:
#    <<: *docker-defaults
#    steps:
#      - setup_remote_docker

workflows:
  version: 2
  deploy:
    jobs:
      - build-image
#      - deploy-dev:
#          requires:
#            - build-image
#          filters:
#            branches:
#              ignore: master
#      - deploy-prod:
#          requires:
#            - build-image
#          filters:
#            branches:
#              only: master
