# Aliases
docker-defaults: &docker-defaults
  docker:
    - image: quay.io/nyulibraries/circleci_docker:18.06.3-dc-1.23.2-0
      environment:
        - IMAGE_NAME=ares-templates
  working_directory: ~/app

build_docker: &build_docker
  run:
    name: Build docker
    command: |
      docker-compose build 

auth_quay: &auth_quay
  run:
    name: Authenticate Quay 
    command: |
      docker login -u "$QUAY_USERNAME" --password "$QUAY_PASSWORD" quay.io

pull_docker: &pull_docker
  run:
    name: Pull Docker
    command: |
      export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
      docker pull quay.io/nyulibraries/${IMAGE_NAME}:${BRANCH_NO_SLASH} || docker pull quay.io/nyulibraries/${IMAGE_NAME}:latest

push_docker: &push_docker
  run:
    name: Push Docker
    command: |
      export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
      docker tag ${IMAGE_NAME} quay.io/nyulibraries/${IMAGE_NAME}:latest
      docker tag ${IMAGE_NAME} quay.io/nyulibraries/${IMAGE_NAME}:${BRANCH_NO_SLASH}
      docker tag ${IMAGE_NAME} quay.io/nyulibraries/${IMAGE_NAME}:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}
      docker push quay.io/nyulibraries/${IMAGE_NAME}:latest
      docker push quay.io/nyulibraries/${IMAGE_NAME}:${BRANCH_NO_SLASH}
      docker push quay.io/nyulibraries/${IMAGE_NAME}:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}

test_dev: &test_dev
  run:
    name: Test Dev
    command: |
      ./test_compile.sh dev

test_prod: &test_prod
  run:
    name: Test Prod
    command: |
      ./test_compile.sh prod

version: 2
jobs:
  build-image:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *pull_docker
      - <<: *build_docker
      - <<: *auth_quay
      - <<: *push_docker
  test-dev:
    <<: *docker-defaults
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "d2:14:48:ee:19:c8:28:1c:7b:3b:bf:ef:16:66:9b:3b"
      - <<: *test_dev
  test-prod:
    <<: *docker-defaults
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "d2:14:48:ee:19:c8:28:1c:7b:3b:bf:ef:16:66:9b:3b"
      - <<: *test_dev

workflows:
  version: 2
  deploy:
    jobs:
      - build-image
      - test-dev:
          requires:
            - build-image
          filters:
            branches:
              ignore: master
      - test-prod:
          requires:
            - build-image
          filters:
            branches:
              only: master
