# Aliases
docker-defaults: &docker-defaults
  docker:
    - image: quay.io/nyulibraries/circleci_docker:18.06.3-dc-1.23.2-0
  working_directory: ~/app

test_dev: &test_dev
  run:
    name: Test Dev
    command: |
      ./test_compile.sh dev

test_prod: &test_prod
  run:
    name: Test Prod
    command: |
      ./test_compile.sh prod

version: 2
jobs:
  test-dev:
    <<: *docker-defaults
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "d2:14:48:ee:19:c8:28:1c:7b:3b:bf:ef:16:66:9b:3b"
      - <<: *test_dev
  test-prod:
    <<: *docker-defaults
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "d2:14:48:ee:19:c8:28:1c:7b:3b:bf:ef:16:66:9b:3b"
      - <<: *test_dev

workflows:
  version: 2
  deploy:
    jobs:
      - test-dev:
          filters:
            branches:
              ignore: master
      - test-prod:
          filters:
            branches:
              only: master
